### PR TITLE
Add markown file support

### PR DESCRIPTION
**Pull request by wikimatze**
Not all elements are covered but the basic ones that are part of most README files.

### CODE REVIEW

**Comment by rking** [comment]
After thinking a bit, I'm having my doubts.

Why don't we use the builtin markdown syntax declarations?

**Comment by wikimatze** [comment]
Does vim has markdown syntax declaration per default or what do you mean?

**Comment by rking** [comment]
Yes, it has a `syntax/markdown.vim`. You can manually trigger it with `:setf markdown`. If `*.md`s get detected as "Modula2" rather than "Markdown", a line like this fixes that:

```
au BufRead,BufNewFile *.md set filetype=markdown
```

Try these things and then see if the vim-detailed formatting is satisfactory, please.

**Comment by wikimatze** [comment]
Thanks for your help, markdown files are already detected as those. I clone the syntax detection file from @plasticboy https://raw.github.com/plasticboy/vim-markdown/master/syntax/mkd.vim and it does what I want. Sorry for my attempt to reinvent the wheel and my attempt to add code to your repository that doesn't have anything to do with colors at all - I see this now.

I'll close this pull request!

**Pull request closed without merging**
